wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709797134.00354
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.6.13
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
